package com.lean56.andplug.app.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.lean56.andplug.app.dao.Msg;

import com.lean56.andplug.app.dao.MsgDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig msgDaoConfig;

    private final MsgDao msgDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        msgDaoConfig = daoConfigMap.get(MsgDao.class).clone();
        msgDaoConfig.initIdentityScope(type);

        msgDao = new MsgDao(msgDaoConfig, this);

        registerDao(Msg.class, msgDao);
    }
    
    public void clear() {
        msgDaoConfig.getIdentityScope().clear();
    }

    public MsgDao getMsgDao() {
        return msgDao;
    }

}
